### ISSUE TITLE
Github bot no longer working

### ISSUE THREAD

**Issue by sebastienvermeille** [invertase/docs.page#329]
Hi for some reason the bot no longer post comments to my PRs anymore.

I have two projects using docs.page both are impacted.

Is the project still alive ?

**Comment by jordan-pieces** [comment]
hey @sebastienvermeille i was facing this same issue and noticed that @Ehesp has been a bit bogged down in other projects, so i created a solution that you can utilize on your repo through a github action to still get the preview link that you need. 

They are still being generated, just not posted to the comments on their own. If you create a workflow file on your repo nested like this: 

```
.github
|-- workflows
|  |-- git-actions.yml
```

then you add the following to that action file: 

```yml
name: <name-your-action-here>
run-name: <name-the-workflow>
on:
  pull_request:
    types: [opened]
jobs:
  post-preview-link:
    runs-on: ubuntu-latest
    steps:
      - name: Comment Preview Link
        uses: thollander/actions-comment-pull-request@v2.4.2
        with:
          message: |
            :wave: Preview link --> https://<your-base-url-here>/~${{ github.event.pull_request.number }}
```

this will just post the proper link to your repos comments when you open up a PR there. It should be pretty straightforward, but depending on your experiences with github actions it can feel a bit off. let me know if you have any questions, and you can check out the action i setup here on this documentation repo:

https://github.com/pieces-app/documentation/actions/runs/6590565620/workflow

also very thankful for this github action here: https://github.com/thollander/actions-comment-pull-request

very useful for a number of other things as well too. let me know if you have any trouble ! :) this should serve as a viable option for now
